// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQC7fDO-2JxLuSQhQsbM94lvU7hLBDBg',
    appId: '1:381977422722:web:0d078f5696a5387e75fd9b',
    messagingSenderId: '381977422722',
    projectId: 'habittracker-baf13',
    authDomain: 'habittracker-baf13.firebaseapp.com',
    storageBucket: 'habittracker-baf13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC34DwaWAnBuchEwS3ZU0gWjxVxh3PXSeM',
    appId: '1:381977422722:android:d8c55da698ae6b4375fd9b',
    messagingSenderId: '381977422722',
    projectId: 'habittracker-baf13',
    storageBucket: 'habittracker-baf13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUeeH7rCke-gu1A8GE5uZzAi8BhBDZzB4',
    appId: '1:381977422722:ios:b9e5f2513ecda88575fd9b',
    messagingSenderId: '381977422722',
    projectId: 'habittracker-baf13',
    storageBucket: 'habittracker-baf13.firebasestorage.app',
    iosBundleId: 'com.example.habittracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUeeH7rCke-gu1A8GE5uZzAi8BhBDZzB4',
    appId: '1:381977422722:ios:b9e5f2513ecda88575fd9b',
    messagingSenderId: '381977422722',
    projectId: 'habittracker-baf13',
    storageBucket: 'habittracker-baf13.firebasestorage.app',
    iosBundleId: 'com.example.habittracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXQC7fDO-2JxLuSQhQsbM94lvU7hLBDBg',
    appId: '1:381977422722:web:394b3a2d39b9486375fd9b',
    messagingSenderId: '381977422722',
    projectId: 'habittracker-baf13',
    authDomain: 'habittracker-baf13.firebaseapp.com',
    storageBucket: 'habittracker-baf13.firebasestorage.app',
  );
}
